[build]
    command = "npm run build"
    publish = "dist"

[context.production.environment]
    NODE_ENV = "production"

[template.environment]
    TZ = "set the timezone for your site, e.g. America/New_York"

[[redirects]]
    from = "*"
    to = "/404"
    status = 404
